"""Tests for the public-snapshot dashboard publisher.

Covers the STEER.md ``dashboard.endpoint_retired`` contract: the
endpoint-coverage dashboard must NOT appear in the public surface
generated by ``scripts/live/publish_dashboards.py``.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "publish_dashboards", REPO_ROOT / "scripts" / "live" / "publish_dashboards.py"
)
publish_dashboards = importlib.util.module_from_spec(SPEC)
sys.modules["publish_dashboards"] = publish_dashboards
SPEC.loader.exec_module(publish_dashboards)  # type: ignore[union-attr]


def test_cards_does_not_contain_endpoint_slug():
    slugs = {c.get("slug") for c in publish_dashboards.CARDS}
    assert "endpoint" not in slugs
    assert "dense" in slugs
    assert "router" in slugs
    assert "agent" in slugs
    assert "marketplace" in slugs


def test_headlines_does_not_contain_endpoint_key():
    assert "endpoint" not in publish_dashboards._HEADLINES


def _split_headline_and_footer(page: str) -> tuple[str, str]:
    """The "headline section" is everything before the <footer> tag.

    STEER.md "Engines shown on the headline" — retired dashboards may
    still leak into a non-headline area (e.g. an appendix), but the
    headline must be clean. We treat the page up to <footer> as the
    headline section for this test.
    """
    marker = "<footer"
    idx = page.find(marker)
    if idx == -1:
        return page, ""
    return page[:idx], page[idx:]


def test_rendered_index_headline_has_no_endpoint_dashboard_string():
    # All cards missing — exercises the same render path as a real
    # publish, just without copying real HTML/JSON into out_dir.
    card_data = [{**c, "ready": False} for c in publish_dashboards.CARDS]
    page = publish_dashboards.render_index(card_data)
    headline, _ = _split_headline_and_footer(page)
    assert "endpoint_dashboard" not in headline
    assert "Endpoint identity-gap dashboard" not in headline
    # Sanity: the three target dashboards still render.
    assert "Dense mismatch dashboard" in headline
    assert "MoE router dashboard" in headline
    assert "Agent trajectory dashboard" in headline


def test_rendered_index_contains_dense_and_moe_matrices():
    """STEER `dashboard.dense_moe_split`: index opens with two graph-first
    matrices labelled Dense (Qwen3-32B) and MoE (Qwen3-30B-A3B)."""
    card_data = [{**c, "ready": False, "payload": {}} for c in publish_dashboards.CARDS]
    page = publish_dashboards.render_index(card_data)
    assert "data-section=\"dense-matrix\"" in page
    assert "data-section=\"moe-matrix\"" in page
    assert "Dense (Qwen3-32B)" in page
    assert "MoE (Qwen3-30B-A3B)" in page
    # Each matrix renders as a tile grid (data-chart hooks on populated
    # tiles; the empty/TBD skeleton still emits the row labels FSDP and
    # MEGATRON).
    assert "FSDP" in page
    assert "MEGATRON" in page


def test_rendered_index_matrix_renders_real_dense_payload():
    """When the dense card carries engine-pair + per-row data, the dense
    matrix surfaces at least one tile with a numeric ESS value."""
    dense_payload = {
        "num_runs": 2,
        "rows": [
            {
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.998,
            },
            {
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "fp8",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.992,
            },
        ],
    }
    card_data = []
    for c in publish_dashboards.CARDS:
        if c["slug"] == "dense":
            card_data.append({**c, "ready": True, "filename": "dense_dashboard.html",
                              "summary": "", "payload": dense_payload})
        else:
            card_data.append({**c, "ready": False, "payload": {}})
    page = publish_dashboards.render_index(card_data)
    assert "data-chart=\"matrix-tile\"" in page
    # FSDP × (bf16 · L40S) tile should render an ESS value (>0.99 → green).
    assert "0.9980" in page or "0.998" in page or "0.992" in page
    assert "mx-good" in page or "mx-warn" in page


def test_megatron_placeholder_when_no_megatron_reports():
    """STEER `dashboard.megatron_placeholder`: with zero Megatron reports
    ingested, every Megatron row tile in both matrices renders the literal
    'TBD — pending HF→Megatron conversion' placeholder string."""
    # A real-ish dense payload with FSDP-only rows; no Megatron rows.
    dense_payload = {
        "rows": [
            {
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.998,
            },
            {
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "fp8",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.992,
            },
        ],
    }
    # Router payload also FSDP-only.
    router_payload = {
        "rows": [
            {
                "model_id": "Qwen/Qwen3-30B-A3B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "router_flip_rate": 0.04,
            },
        ],
    }
    card_data = []
    for c in publish_dashboards.CARDS:
        if c["slug"] == "dense":
            card_data.append({**c, "ready": True, "filename": "dense_dashboard.html",
                              "summary": "", "payload": dense_payload})
        elif c["slug"] == "router":
            card_data.append({**c, "ready": True, "filename": "router_dashboard.html",
                              "summary": "", "payload": router_payload})
        else:
            card_data.append({**c, "ready": False, "payload": {}})
    page = publish_dashboards.render_index(card_data)
    # Placeholder literal exactly as the STEER directive requires.
    placeholder = publish_dashboards.MEGATRON_PLACEHOLDER
    assert placeholder == "TBD — pending HF→Megatron conversion"
    # Megatron row tiles must show the placeholder. With one column in
    # each matrix (bf16 / fp8 in dense, bf16 in moe), at least 2 tiles
    # land in the Megatron row across the two matrices.
    occurrences = page.count(placeholder)
    assert occurrences >= 3, (
        f"expected ≥3 Megatron placeholder tiles across both matrices; "
        f"got {occurrences}"
    )
    # The placeholder tile is the TBD style — greyed / dashed.
    assert "mx-tile mx-tbd" in page
    # Every Megatron row tile must contain the placeholder. We use the
    # data-trainer="megatron" marker emitted by `_matrix_tile`.
    import re

    megatron_tiles = re.findall(
        r'<a class="mx-tile[^"]*"[^>]*data-trainer="megatron"[^>]*>(.*?)</a>',
        page,
        flags=re.DOTALL,
    )
    assert megatron_tiles, "expected at least one Megatron row tile"
    for tile_inner in megatron_tiles:
        assert placeholder in tile_inner, (
            f"Megatron tile missing placeholder: {tile_inner!r}"
        )


def test_dense_and_moe_matrices_are_model_bound():
    """STEER `dashboard.matrix_per_model`: each matrix only ingests rows
    whose `model_id` belongs to that matrix's model. A Qwen3-30B-A3B row
    accidentally living in `dense_dashboard.json` must not surface in the
    Dense matrix, and a Qwen3-32B row in `router_dashboard.json` must not
    surface in the MoE matrix.
    """
    import re

    dense_payload = {
        "rows": [
            {
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.9981,
            },
            {
                # Cross-model contaminant: MoE row that must NOT land in dense.
                "model_id": "Qwen/Qwen3-30B-A3B",
                "rollout_engine": "vllm",
                "trainer_engine": "megatron-lm",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "ess": 0.4242,
            },
        ],
    }
    router_payload = {
        "rows": [
            {
                "model_id": "Qwen/Qwen3-30B-A3B",
                "rollout_engine": "vllm",
                "trainer_engine": "megatron",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "router_flip_rate": 0.0723,
            },
            {
                # Cross-model contaminant: dense row that must NOT land in MoE.
                "model_id": "Qwen/Qwen3-32B",
                "rollout_engine": "vllm",
                "trainer_engine": "fsdp",
                "precision_class": "bf16",
                "device_bucket": "L40S (g6e.12xlarge)",
                "router_flip_rate": 0.9999,
            },
        ],
    }
    card_data = []
    for c in publish_dashboards.CARDS:
        if c["slug"] == "dense":
            card_data.append({**c, "ready": True, "filename": "dense_dashboard.html",
                              "summary": "", "payload": dense_payload})
        elif c["slug"] == "router":
            card_data.append({**c, "ready": True, "filename": "router_dashboard.html",
                              "summary": "", "payload": router_payload})
        else:
            card_data.append({**c, "ready": False, "payload": {}})
    page = publish_dashboards.render_index(card_data)

    dense_match = re.search(
        r'<section class="mx-section" data-section="dense-matrix">(.*?)</section>',
        page,
        flags=re.DOTALL,
    )
    moe_match = re.search(
        r'<section class="mx-section" data-section="moe-matrix">(.*?)</section>',
        page,
        flags=re.DOTALL,
    )
    assert dense_match and moe_match, "expected both matrix sections to render"
    dense_section = dense_match.group(1)
    moe_section = moe_match.group(1)

    # Dense matrix: keeps the Qwen3-32B ESS value, drops the MoE row's value.
    assert "0.9981" in dense_section
    assert "0.4242" not in dense_section, (
        "MoE-model row leaked into the Dense matrix"
    )

    # MoE matrix: keeps the Qwen3-30B-A3B router_flip_rate, drops the dense row.
    # router_flip_rate=0.0723 → "7.2%" in the rendered tile.
    assert "7.2%" in moe_section
    assert "0.9999" not in moe_section
    assert "100.0%" not in moe_section, (
        "Dense-model row leaked into the MoE matrix"
    )

    # The cross-model Megatron row in dense_payload would otherwise have
    # populated the Megatron row of the Dense matrix; with the filter the
    # Megatron row in Dense must still render the TBD placeholder.
    placeholder = publish_dashboards.MEGATRON_PLACEHOLDER
    megatron_tiles_in_dense = re.findall(
        r'<a class="mx-tile[^"]*"[^>]*data-trainer="megatron"[^>]*>(.*?)</a>',
        dense_section,
        flags=re.DOTALL,
    )
    assert megatron_tiles_in_dense, "expected Megatron row tiles in Dense matrix"
    for inner in megatron_tiles_in_dense:
        assert placeholder in inner, (
            "Dense Megatron tile lost its placeholder — MoE row contaminated it"
        )


def test_rendered_index_with_ready_cards_has_no_endpoint_link():
    card_data = []
    for c in publish_dashboards.CARDS:
        card_data.append({
            **c,
            "ready": True,
            "filename": f"{c['slug']}_dashboard.html",
            "summary": "",
            "payload": {},
        })
    page = publish_dashboards.render_index(card_data)
    headline, _ = _split_headline_and_footer(page)
    assert "endpoint_dashboard.html" not in headline
    assert "endpoint_dashboard" not in headline
