"""Tests for the public-snapshot dashboard publisher.

Covers the STEER.md ``dashboard.endpoint_retired`` contract: the
endpoint-coverage dashboard must NOT appear in the public surface
generated by ``scripts/live/publish_dashboards.py``.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "publish_dashboards", REPO_ROOT / "scripts" / "live" / "publish_dashboards.py"
)
publish_dashboards = importlib.util.module_from_spec(SPEC)
sys.modules["publish_dashboards"] = publish_dashboards
SPEC.loader.exec_module(publish_dashboards)  # type: ignore[union-attr]


def test_cards_does_not_contain_endpoint_slug():
    slugs = {c.get("slug") for c in publish_dashboards.CARDS}
    assert "endpoint" not in slugs
    assert "dense" in slugs
    assert "router" in slugs
    assert "agent" in slugs
    assert "marketplace" in slugs


def test_headlines_does_not_contain_endpoint_key():
    assert "endpoint" not in publish_dashboards._HEADLINES


def _split_headline_and_footer(page: str) -> tuple[str, str]:
    """The "headline section" is everything before the <footer> tag.

    STEER.md "Engines shown on the headline" — retired dashboards may
    still leak into a non-headline area (e.g. an appendix), but the
    headline must be clean. We treat the page up to <footer> as the
    headline section for this test.
    """
    marker = "<footer"
    idx = page.find(marker)
    if idx == -1:
        return page, ""
    return page[:idx], page[idx:]


def test_rendered_index_headline_has_no_endpoint_dashboard_string():
    # All cards missing — exercises the same render path as a real
    # publish, just without copying real HTML/JSON into out_dir.
    card_data = [{**c, "ready": False} for c in publish_dashboards.CARDS]
    page = publish_dashboards.render_index(card_data)
    headline, _ = _split_headline_and_footer(page)
    assert "endpoint_dashboard" not in headline
    assert "Endpoint identity-gap dashboard" not in headline
    # Sanity: the three target dashboards still render.
    assert "Dense mismatch dashboard" in headline
    assert "MoE router dashboard" in headline
    assert "Agent trajectory dashboard" in headline


def test_rendered_index_router_flip_rate_placeholder_visible():
    """The expert-routing TBD slot must render in the headline so readers
    know the metric is coming. Documents the vLLM 0.20.x OpenAI shim
    limitation (no routed_experts) as the why."""
    card_data = [{**c, "ready": False, "payload": {}} for c in publish_dashboards.CARDS]
    page = publish_dashboards.render_index(card_data)
    assert 'data-section="router-flip-rate-placeholder"' in page
    placeholder_start = page.find('data-section="router-flip-rate-placeholder"')
    section_end = page.find("</section>", placeholder_start)
    section_html = page[placeholder_start:section_end]
    assert "Router flip rate" in section_html
    assert "TBD" in section_html
    assert "routed_experts" in section_html
    assert "vLLM" in section_html
    # The legacy cycle-2 matrices are retired entirely.
    assert "data-section=\"dense-matrix\"" not in page
    assert "data-section=\"moe-matrix\"" not in page
    # The Hermes Agent matrices remain the headline.
    assert "Hermes Agent — Dense (Qwen3-32B)" in page
    assert "Hermes Agent — MoE (Qwen3-30B-A3B)" in page


def test_rendered_index_with_ready_cards_has_no_endpoint_link():
    card_data = []
    for c in publish_dashboards.CARDS:
        card_data.append({
            **c,
            "ready": True,
            "filename": f"{c['slug']}_dashboard.html",
            "summary": "",
            "payload": {},
        })
    page = publish_dashboards.render_index(card_data)
    headline, _ = _split_headline_and_footer(page)
    assert "endpoint_dashboard.html" not in headline
    assert "endpoint_dashboard" not in headline
